### ISSUE TITLE
Sidebar displays improperly on locationbar-less chrome pages

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#1]
For example, the Add-ons Manager page, and about:permissions.

In these cases we should probably hide the sidebar entirely.

**Comment by mhammond** [comment]
I had a stab at this and have it mainly working in a branch bug/1-hide-on-locationbarless-chrome.

The problem with this is when the initial tab is locationbar less - eg, if about:addons is the selected tab and you then restart.  It works fine in all other cases I have tried, including when you re-select that first tab.

It seems like there must be a better way though - grabbing a web progress listener seems long winded.  I tried chaning for DOMAttributeChanged events etc but couldn't work out a better way.  I'm over this now, so pushed the branch so I (or anyone!) can revisit.

**Comment by mhammond** [comment]
Finally found where this stuff is hidden by the browser - browser.js in an onLocationChange handler - which simplified things alot.  pushed as rev 95f8558
