### ISSUE TITLE
Notifications do not indicate service provider

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#10]
When we use the MozAlerts service to display notifications, we get an icon, a title, and some text.  If we let the service provider specify all three of those, we don't have a way to badge a notification with either Firefox or the service provider's name.

This can be good, in that it means the notification is all user-centric data (a face of someone I know, and a message I want to hear about them), but it could lead to confusion ("what service is showing me this?") and, in the worst case, abuse.

We should consider lightweight ways of "badging" the notification element to make this connection more clear, especially on desktop OSes where the notification elements are quite generic.

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755138
