### ISSUE TITLE
Ensure that service provider metadata management is forward-compatible with Share

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#11]
Whatever we do to manage service provider metadata should evolve naturally from our Share implementation.

**Comment by mixedpuppy** [comment]
right now there different db files for the addons, but the manifest code is essentially the same.  we just need to define a manifest format, preferably compatible with the apps manifest.  I should refactor the manifest code a bit so the lib file for it remains the same between the two.

**Comment by mixedpuppy** [comment]
Here's a strawman proposal for manifest syntax, which shouldn't interfere with app manifest structure:

{
'browserServices':
{
'activities': {
 'share': { ... }
}
'social': {
 'name': 'mysite',
 'iconURL': ...
 'workerURL': ...
 'sidebarURL': ...
 'URLPrefix': ...
}
}
}

**Comment by mixedpuppy** [comment]
recent changes, documented in https://github.com/mozilla/socialapi-dev/blob/develop/docs/socialAPI.md avoids conflict with share and webapps manifest data
