### ISSUE TITLE
Minimized sidebar has incorrect height if bookmark bar is visible

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#14]
On Mac for certain; have to check elsewhere.

**Comment by mhammond** [comment]
This is fixed in rev 39afe348 - although see issue 18 for some caveats.  It should also be fixed when any other toolbar is at the bottom and when "tabs on top" is not selected.

**Comment by michaelrhanson** [comment]
This fix is not working for me (on Mac Aurora, anyway).  The "impossible" exception, "failed to find the anchor", is throwing.

I'm working around it with return document.getElementById('nav-bar') in the "impossible" condition for now; what's the right fix?

**Comment by michaelrhanson** [comment]
I'm going to close this since our current toolbar strategy does not have this issue.
