### ISSUE TITLE
service window behaviour on service deactivation

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/socialapi-dev#17]
If there are serviceWindows open, should the user be given a chance to confirm before deactivating the service, since this will terminate the windows (which could mean cutting off a chat)?

**Comment by mhammond** [comment]
IMO:
- If the user deactivates we should not confirm _unless_ we can determine there is something that will be lost.  If we can't determine that and ask just-in-case, the user is likely to blindly OK the confirmation anyway.
- If deactivation happens implicitly we should confirm - but I don't think there is a way it gets automatically disabled, so this doesn't apply.

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755129
