### ISSUE TITLE
Enabling addon in the Addons Manager page renders sidebar incorrectly

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#2]
As a consequence of issue #1, when we re-activate the addon, it puts the sidebar in the wrong place (probably because "nav" is hidden).

Reflowing the layout fixes the issue; a fix for #1 might just clear this up.

**Comment by mhammond** [comment]
FWIW, I don't see this problem on Windows.

**Comment by mixedpuppy** [comment]
I cannot repro at this stage, closing
