### ISSUE TITLE
Auto-hide sidebar on provider's site?

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#20]
We have talked about providing a JS or header-based cue to a site to let it know we are displaying a sidebar.  Until we have that figured out, I think we should probably just auto-hide the sidebar when the user visits the provider's site.

How should this be implemented? We could use the prefixURL of the provider metadata, but that's more likely just the part of the site that implements the sidebar and serviceWindows.  We could do a domain match, but that's likely to run afoul of http/https variation.  Perhaps we should just match on the domain name.

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755131
