### ISSUE TITLE
Personas can confuse sidebar layout logic

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#23]
This one, for example: http://www.getpersonas.com/en-US/persona/16

**Comment by mhammond** [comment]
FWIW, I don't see this problem - even before the latest fix to find the bottom toolbar, things seem to look exactly the same both with and without the persona installed.

**Comment by michaelrhanson** [comment]
mark, try turning on the bookmarks toolbar with that persona.  That shows the breakage - should have mentioned that first.

**Comment by mhammond** [comment]
Yep - tried that and tried all other combinations I could think of (tabs on top, all other toolbars shown/hidden).  Do you also see it on Windows?

**Comment by michaelrhanson** [comment]
I'm going to close this, as our current toolbar-item strategy doesn't get confused by this.
