### ISSUE TITLE
ArrayBuffer/Uint8Array stuff not working in nightly

### ISSUE THREAD

**Issue by mhammond** [mozilla/socialapi-dev#24]
Nightly from the last day or 2 is having issues with our ArrayBuffer/Uint8Array dances.  The problem manifests itself as errors:

2012-03-28T07:01:50.339Z [mqtt]: Malformed message
2012-03-28T07:01:50.343Z [mqtt]: ERROR parsing onmessage: TypeError: parsedCommand is undefined

digging deeper the problem is connection.parse is attempting to parse zero bytes.  Digging deeper still - I changed the first few lines of connection.parse to read:

  mqttlog("got a rawBuffer with size " + rawBuffer.byteLength);
  var buf = new Uint8Array(rawBuffer);
  mqttlog("resulting array has size " + buf.length);

and the output from this is:

2012-03-28T06:59:53.661Z [mqtt]: got a rawBuffer with size 4
2012-03-28T06:59:53.664Z [mqtt]: resulting array has size 0

So somehow we are getting a zero byte array from a 4 byte message buffer.  A trivial test can't reproduce this.

_sigh_

**Comment by mhammond** [comment]
"fixing" that assertion in nightly seems to have caused us to then hit bug 734215 which Mike opened earlier this month.  _double sigh_

**Comment by michaelrhanson** [comment]
I note that the current workaround does not work:

`2012-05-07T22:10:08.395Z [mqtt]: ERROR parsing onmessage: TypeError: workerWindow.Uint8Array is not a constructorStack trace: 
([object Proxy])@resource://socialdev/modules/frameworker.js:430`

line #430 is:

```
        // And a very hacky work-around for bug 734215
        workerWindow.bufferToArrayHack = function(a) {
            return new workerWindow.Uint8Array(a);
        };
        sandbox.importFunction(workerWindow.bufferToArrayHack, "bufferToArrayHack");
```

**Comment by michaelrhanson** [comment]
Whoops, clicked the wrong button.  NOT closed.

**Comment by mhammond** [comment]
I can't repro this anywhere and Shane doesn't seem to be able to either.  I also changed fbworker.js:

```
   // var buf = new Uint8Array(rawBuffer);
   var buf = bufferToArrayHack(rawBuffer);
+  dump("bufferToArrayHack made " + buf + "\n");
```

and it constantly prints:

bufferToArrayHack made [object Uint8Array]

This is in FF, Aurora and Nightly, all up-to-date.  So I'm not sure what is going on...

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755122
