### ISSUE TITLE
New windows should start with sidebar minimized (?)

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#25]
I think having the sidebar pop open on every new window will lead to annoyance.  Let's default to minimized.

**Comment by mixedpuppy** [comment]
that's going to confuse a whole lot of state mechanism in the code.  right visibility state is global, not per window.

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755136
