### ISSUE TITLE
recommend button needs to reset when url changes

### ISSUE THREAD

**Issue by mhammond** [mozilla/socialapi-dev#27]
spec calls for, and it's implemented, that after a "user-recommend", the service may respond with a user-recommend-prompt-response so the icon and message change to reflect the action.  However, while the recommend widget honors the second prompt response, it doesn't arrange to reset the prompt back to the default when URL changes (eg, tab switch, navigation, etc).

ie, if the server responds with a "you liked this!" after clicking, that new text would stay there forever!

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755117
