### ISSUE TITLE
disable history in the sidebar panel.

### ISSUE THREAD

**Issue by mhammond** [mozilla/socialapi-dev#29]
Rev 73ecfd1 enables history in the sidebar panel to work around a problem with one of our partners.  Apparently, with history disabled, window.history.replaceState exists but throws an exception.  Our partner is expecting that if it is disabled window.history or window.history.replaceState should be undefined.  We should confirm that, confirm it is a bug in Firefox and re-disable once fixed.

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755116
