### ISSUE TITLE
Cookie Access in Worker

### ISSUE THREAD

**Issue by pvagata** [mozilla/socialapi-dev#37]
(Per discussion with Mark) setting up an issue to track this: Without access to cookies in the worker, the chrome-jewels can only be updated when the sidebar is loaded, since the worker won't be able to determine whether the user is logged in/out.

**Comment by mhammond** [comment]
Best I can tell, workers don't have access to cookies.  It also seems like xhr in a worker isn't going to use them.  So in mail to Pam, I suggested an option is to have a social.get-cookies message.  While we currently _do_ expose localStorage, I'm not even sure that exists in the worker spec, so we might also need something similar for that.
