### ISSUE TITLE
popup windows should not have sidebar

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#4]
We should determine when a window.open call is intended to create a "popup" window, and not insert the sidebar in this case.  At a minimum, the absence of the "toolbar" feature should be used as a clue.

**Comment by mhammond** [comment]
check for toolbar being visible in rev 627c4b4.  According to http://mxr.mozilla.org/mozilla-central/source/browser/base/content/browser.js#1360 that is the canonical check, so seems reasonable for now.

**Comment by michaelrhanson** [comment]
Reopening; I still see sidebar in some advertising popups.  The location bar was present but no navigation controls.

**Comment by mixedpuppy** [comment]
Do we have a solid repro for this?

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755139
