### ISSUE TITLE
potential redirect loop while preventing sidebar from changing domains

### ISSUE THREAD

**Issue by mhammond** [mozilla/socialapi-dev#5]
We have a location change watcher to ensure the sidebar never moves from the correct domain.  If it detects such movement it does a goBack() call to take us back to the correct domain.

Consider a scenario where a page on the correct domain ends up doing a redirect to a page off the domain.  When we do goBack() we wind up back at the page doing the redirect, so the process would repeat indefinitely.

A possible solution might be to always return to the "start" page for the service - although that would suffer the same problem in the (unlikely) case the main page does a redirect.

**Comment by mixedpuppy** [comment]
fixed by getting the location change intercepting corrected
