### ISSUE TITLE
display SSL badging on servicewindow

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#6]
The servicewindow does not currently display the SSL badging; I suggest that we use the technique previously prototyped in OAuthorizer to place a permanent location badge and trigger point for a certificate-display popup.

**Comment by mixedpuppy** [comment]
I pulled in the related code from oauthorizer and have a security statusbar now.  UX is necessary.

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755125
