### ISSUE TITLE
Implement displayed-service switching from popup

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#7]
The social browsing popup should allow the user to switch the displayed service for its window; this should refocus the sidebar to the selected service and refocus the webProgressListener for the sidebar's browser.  It should also refresh the recommend icon.

**Comment by mixedpuppy** [comment]
I'm not clear what popup you're talking about.  The toolbar button menu?

If it is the toolbar button, this should all be done now.  the recommend icon is switching, and you can switch between services.

**Comment by mixedpuppy** [comment]
clarified, this is done
