### ISSUE TITLE
Implement service active/inactive toggling from popup

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#8]
The social browsing popup should have a single-click way to switch between an active/inactive state.  

When a service goes inactive, all of its serviceWindows should be closed, its Sidebars should be closed, and its Worker should be shut down.  Any Sidebars that are displaying content from the provider should be closed (i.e. the sidebar element's browser should be set to a blank page, and the sidebar should be hidden).  The Worker should be the last resource to close.

Open question: If the user has multiple service providers active and deactivates the currently visible one, should the sidebar switch to the next one in the list, or be hidden?  Will flag as UX issue.

Open question: If there are serviceWindows open, should the user be given a chance to confirm before deactivating the service, since this will terminate the windows (which could mean cutting off a chat)?

**Comment by mhammond** [comment]
most of this is now working - all sidebars hide and the worker terminates.  Open questions remain open though, so I'm also leaving this open!

**Comment by mixedpuppy** [comment]
I'm working on simplifying the interactions here, they were too confusing before.  I've pushed a set of changes to the toolbar button already, but am still working out some of the interactions.  basically, the interactions are:
- minimize/maximize (current hide/show of the browser)
- enable/disable (all social browsing)
- selecting service to show
- preferences

In preferences, you can enable/disable each service selectively.

**Comment by mixedpuppy** [comment]
I moved the open questions to other issues, and am closing this.
