### ISSUE TITLE
Implement "service preference" page

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/socialapi-dev#9]
Either as a preference pane, or as about:social, we should have a place where the user can see all of the available providers.

This display should include, for each provider:
- name, icon, and domain name
- whether it is currently active, and a button to activate/deactivate
- whether it will be activated at browser startup
- whether notifications from the provider are allowed
- perhaps the most recent notifications?  do we store them for a while?
- a way to delete the provider from the list

**Comment by mixedpuppy** [comment]
in the activities addon I have a very raw enable/disable page, it could be moved to this pretty easily

**Comment by mixedpuppy** [comment]
moved to https://bugzilla.mozilla.org/show_bug.cgi?id=755126
